
default: &default
  adapter: postgresql
  username: postgres
  password: root  
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: movie_review


test:
  <<: *default
  database: movie_review

production:
  <<: *default
  database: movie_review
